In [1]:
import pandas as pd

In [2]:
file='C:/Users/psk/3rd_backup/kream_detail_pro8.csv'

In [3]:
df = pd.read_csv(file)
df

,_id,brand,prod_kr_name,rescent_price,model_no,release_date,colors,release_price,instant_buy_price,instant_sell_price,img_url
0,Jordan 1 Low Vintage Grey,Jordan,조던 1 로우 빈티지 그레이,200000,553558-053,1900-01-01,GREY/WHITE/CREAM,129000,202000,201000,https://kream-phinf.pstatic.net/MjAyMjA2MjdfMT...
1,Jordan 1 x Travis Scott x Fragment Retro Low O...,Jordan,조던 1 x 트래비스 스캇 x 프라그먼트 레트로 로우 OG SP 밀리터리 블루,1555000,DM7866-140,2021-08-13,SAIL/BLACK/MILITARY BLUE,189000,1540000,2230000,https://kream-phinf.pstatic.net/MjAyMTA3MzBfNT...
2,Jordan 1 Retro High OG Black Mocha,Jordan,조던 1 레트로 하이 OG 블랙 모카,702000,555088-105,2020-11-13,SAIL/DARK MOCHA-BLACK-BLACK,199000,600000,818000,https://kream-phinf.pstatic.net/MjAyMDEwMjJfOC...
3,Jordan 4 Retro White and Black,Jordan,조던 4 레트로 화이트 앤 블랙,312000,DH6927-111,2022-05-23,WHITE/BLACK/NEUTRAL GREY,249000,299000,313000,https://kream-phinf.pstatic.net/MjAyMjA1MDlfOD...
4,Jordan 1 Retro High OG Bleached Coral,Jordan,조던 1 레트로 하이 OG 블리치드 코랄,244000,555088-108,2022-05-14,WHITE/BLACK/GREY FOG/BLEACHED CORAL,209000,207000,270000,https://kream-phinf.pstatic.net/MjAyMjA1MDlfMT...
...,...,...,...,...,...,...,...,...,...,...,...
2988,Jordan 1 Retro High OG SP Gina (Special Box),Jordan,조던 1 레트로 하이 OG SP 지나 (스페셜 박스),0,CD7071-001,2019-05-25,BLACK/BLACK-WHITE-VARSITY RED,234600,0,0,https://kream-phinf.pstatic.net/MjAyMTAyMjJfMS...
2989,Jordan 13 Retro Low Quai 54,Jordan,조던 13 레트로 로우 콰이 54,0,810551-050,2015-06-14,BLACK/DARK GREY-WHITE-CHROME,325200,0,0,https://kream-phinf.pstatic.net/MjAyMDEwMjJfMj...
2990,(GS) Jordan 11 Retro Heiress Velvet,Jordan,(GS) 조던 11 레트로 헤어리스 벨벳,290000,852625-650,2016-12-18,NIGHT MAROON/METALLIC GOLD-NIGHT MAROON,286200,340000,180000,https://kream-phinf.pstatic.net/MjAyMDEwMjJfND...
2991,Jordan 1 Retro High Flyknit Derek Jeter RE2PECT,Jordan,조던 1 레트로 하이 플라이니트 데릭 지터 RE2PECT,350000,AH7233-105,2018-02-24,SAIL/METALLIC GOLD-MIDNIGHT NAVY,234100,380000,150000,https://kream-phinf.pstatic.net/MjAyMDEwMjJfNT...
2992,(GS) Jordan 1 Retro High Melo,Jordan,(GS) 조던 1 레트로 하이 멜로,229000,705300-026,2014-12-20,BLACK/METALLIC GOLD-WHITE,143100,299000,0,https://kream-phinf.pstatic.net/MjAyMDEwMjJfMj...

In [4]:
df.columns

Index(['_id', 'brand', 'prod_kr_name', 'rescent_price', 'model_no',
       'release_date', 'colors', 'release_price', 'instant_buy_price',
       'instant_sell_price', 'img_url'],
      dtype='object')

In [5]:
df1= df.loc[:,['model_no', 'rescent_price','release_price', 'instant_buy_price','instant_sell_price']]
df1

,model_no,rescent_price,release_price,instant_buy_price,instant_sell_price
0,553558-053,200000,129000,202000,201000
1,DM7866-140,1555000,189000,1540000,2230000
2,555088-105,702000,199000,600000,818000
3,DH6927-111,312000,249000,299000,313000
4,555088-108,244000,209000,207000,270000
...,...,...,...,...,...
2988,CD7071-001,0,234600,0,0
2989,810551-050,0,325200,0,0
2990,852625-650,290000,286200,340000,180000
2991,AH7233-105,350000,234100,380000,150000
2992,705300-026,229000,143100,299000,0

In [6]:
def strip_pro(data):
    data = data.strip()
    return data

In [7]:
df1['model_no']= df1['model_no'].apply(strip_pro)
df1

,model_no,rescent_price,release_price,instant_buy_price,instant_sell_price
0,553558-053,200000,129000,202000,201000
1,DM7866-140,1555000,189000,1540000,2230000
2,555088-105,702000,199000,600000,818000
3,DH6927-111,312000,249000,299000,313000
4,555088-108,244000,209000,207000,270000
...,...,...,...,...,...
2988,CD7071-001,0,234600,0,0
2989,810551-050,0,325200,0,0
2990,852625-650,290000,286200,340000,180000
2991,AH7233-105,350000,234100,380000,150000
2992,705300-026,229000,143100,299000,0

In [8]:
df1.to_csv('C:/Users/psk/3rd_backup/ERD_table/price_table.csv', index=False, encoding='cp949')